import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <nav className="sticky top-0 z-50 bg-white shadow-md border-b border-gray-200 py-3 px-6 flex items-center justify-between">
          <div className="text-2xl font-extrabold tracking-tight text-blue-700 select-none">
            RecruitPro
          </div>
          {/* You can add more nav items or user info here if needed */}
        </nav>
        {children}
      </body>
    </html>
  );
}
